# See doc/docker/README.md or https://github.com/instructure/canvas-lms/tree/master/doc/docker
version: '2.3'
services:
  web: &WEB
    container_name: web
    ports:
      - 41322:80
    build:
      context: .
    links:
      - postgres
      - redis
    environment:
      POSTGRES_PASSWORD: sekret

  jobs:
    <<: *WEB
    command: bundle exec script/delayed_job run

  postgres:
    container_name: postgres
    build: ./docker-compose/postgres
    environment:
      POSTGRES_PASSWORD: sekret

  redis:
    container_name: redis
    image: redis:alpine
